### ISSUE TITLE
Supervisor Meeting - September 25 2023 @ 9:30AM

### ISSUE THREAD

**Issue by Computerized** [davimang/REACH#3]
### Topics of Discussion:
- Scheduling of meetings
- Licensing and IP
- Requirements gathering

**Comment by AKP101** [comment]
**Requirements:**
- Take info from clinicaltrials .gov and needs to incorporate that into the search
- Some kind of location component so that patient can get closest studies (research opportunities with 10km, 20 km etc...)
- limit ourselves to lung and pulmonary conditions at first
**Patient Req:**
- Open up web page and punch in demographics: age, medical condition, given contact person, link
- Patient would be better to have account and save condition
- Templated email to contact researcher, to send over to researcher
- Email notification system (optional) for studies in the area. 
- VERY user friendly and simple!
- Knowledge barrier for patients
- Explain to a patient how trials go using FAQ
**Clinician:**
- A little bit of additional patient detail: age, medical condition, given contact person, link
- Very detailed, because you need a doctor to be able to recommend the right study to the patient
- The onus falls on the patient/clinician to contact the researcher
- Email notification system (optional) for studies in the area. 
- Time and usability is a big problem for clinicians.
**Aside:** 
- Talk to a patient and get any questions they have about research
- Might be easier to do a website but more intuitive to do a webapp
- Website as a first step very button heavy makes sense

Set a biweekly meeting.
