### ISSUE TITLE
Research routing in REACT (react router)

### ISSUE THREAD

**Issue by Computerized** [davimang/REACH#34]
issue description below

**Comment by aami-hus** [comment]
react router seems to be an efficient solution to switch between webpages we want to display. this issue was opened to research react router and how plausible it would be to integrate it with the REACH project.

Notes:
- efficient
- no need to keep track of state or pass props down all the way from the main component
- all routes (to different pages) can be defined in main component
- also inadvertently implements history stack so users can go back/forward through pages they've viewed
